apiVersion: v1
kind: Service
metadata:
  name: adminer-service-nodeport
spec:
  type: LoadBalancer
  selector:
    app: adminer
  ports:
    - port: 80                
      targetPort: 8080 
      protocol: TCP