apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
 name: EKSCLUSTER
 region: ap-southeast-1

vpc:
 clusterEndpoints:
   publicAccess:  true
   privateAccess: true

nodeGroups:
 - name: nodepool-spiderman
   instanceType: t3.medium
   desiredCapacity: 2
